
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.156.128.134:3306/lottery?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: 'classpath*:mappers/**/*.xml'
  mapper-scan: 'com.cj.lottery'

server:
  port: 80

logging:
  config: classpath:logback-spring.xml
#debug: true

#######微信公众号配置信息
app:
  weixin:
    gzh:
      appid: '123'
      secret: '222'
    pay:
      appid: '22'
      mchid: '11'
      notifyUrl: ''
      url: 'https://api.mch.weixin.qq.com/v3/pay/transactions/jsapi'
  domain:
      url: 'http://www.baidu.com'

###### 阿里云短信
aliyun:
  accessKeyId: ''
  secret: ''
  signName: ''
  templateCode: ''
  paramName: ''
