server:
  port: 8086
  servlet:
    context-path: /lottery

#########数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.80.82:3306/lottery?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dbuser
    password: '@#23wesdxc'
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true
    profiles:
      active: ali
  druid:
    #2.连接池配置
    #初始化连接池的连接数量 大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    #配置获取连接等待超时的时间
    max-wait: 60000
    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 30000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false
    # 是否缓存preparedStatement，也就是PSCache  官方建议MySQL下建议关闭   个人建议如果想用SQL防火墙 建议打开
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filter:
      stat:
        merge-sql: true
        slow-sql-millis: 2000
    #3.基础监控配置
    web-stat-filter:
      enabled: true
      url-pattern: /*
#    stat-view-servlet:
#      enabled: true                   # 启用StatViewServlet
#      url-pattern: /druid/*           # 访问内置监控页面的路径，内置监控页面的首页是/druid/index.html
#      reset-enable: false              # 不允许清空统计数据,重新计算
#      login-username: root            # 配置监控页面访问密码
#      login-password: 123
#      allow: 127.0.0.1           # 允许访问的地址，如果allow没有配置或者为空，则允许所有访问
#      deny:


#  profiles:
#    active: pro



#######mybatis-plus配置
mybatis-plus:
  mapper-locations: 'classpath*:mappers/**/*.xml'
  mapper-scan: 'com.cj.lottery'
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

########log4j日志配置
logging:
  config: classpath:logback-spring.xml
#  file:
#    path:

#######微信公众号配置信息
app:
  weixin:
    gzh:
      appid: wx4f43a6c5c3b7fe13
      secret: cb5d31f7c17c06e99b28bd39b5b289c1
    pay:
      appid: '22'
      mchid: '11'
      notifyUrl: ''
    refund:
      notifyUrl: '/lottery/api/pay/callbacks/refund'
  domain:
    url: https://bbox.92pr.cn/lottery

###### 阿里云短信
msg:
  account: al0001
  password: al0001
  sendMsgUrl: http://211.149.255.237:81/smsJson.aspx
#  templateCode: ''
#  paramName: ''


  ### 微信支付
wechat:
  pay:
    v3:
      # 租户id
      lottery:
        # 应用appId 必填
        app-id: wx41c40c70db4b6774
        # v2 api 密钥  1.0.5版本以后如果用到V2的接口时必填，单纯V3不需要
        app-secret: felordcn
        # api v3 密钥 必填
        app-v3-secret: 1JvpMFrKoUqAuiSyPe3kzUbsKPiu34QB
        # 微信支付商户号 必填
        mch-id: 1607180898
        # 商户服务器域名 用于回调  回调路径为 domain + notifyUrl  需要放开回调接口的安全策略 必填
        domain: https://m.keyundz.cn
        # 商户 api 证书路径 必填  填写classpath路径 位于 maven项目的resources文件下
        cert-path: wechat/apiclient_cert.p12
#        notify-url: https://m.keyundz.cn/lottery/api/pay/callbacks/transaction

ali:
  pay:
    v1:
      app-id: 2021002140657575
      app-private-key-path: alipay-sandbox/app_rsa
      alipay-public-cert-path: alipay-sandbox/alipayCertPublicKey_RSA2.crt
      alipay-root-cert-path: alipay-sandbox/alipayRootCert.crt
      app-cert-public-key-path: alipay-sandbox/appCertPublicKey_2021002140657575.crt
      # 沙盒测试网关  正式请移除server-url 配置即可
      server-url: https://openapi.alipay.com/gateway.do
      charset: UTF-8
      format: json
      sign-type: RSA2
      notify: https://m.keyundz.cn/lottery/api/pay/callbacks/aliNotify
