server:
  port: 80

#########数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.156.128.134:3306/lottery?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true
    profiles:
      active: wechat


#######mybatis-plus配置
mybatis-plus:
  mapper-locations: 'classpath*:mappers/**/*.xml'
  mapper-scan: 'com.cj.lottery'
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

########log4j日志配置
logging:
  config: classpath:logback-spring.xml

#######微信公众号配置信息
app:
  weixin:
    gzh:
      appid: '123'
      secret: '222'
    pay:
      appid: '22'
      mchid: '11'
      notifyUrl: ''
    refund:
      notifyUrl: ''
  domain:
      url: 'http://www.baidu.com'

###### 阿里云短信
aliyun:
  accessKeyId: ''
  secret: ''
  signName: ''
  templateCode: ''
  paramName: ''


  ### 微信支付
wechat:
  pay:
    v3:
      # 租户id
      lottery:
        # 应用appId 必填
        app-id: wx554b6b******54312
        # v2 api 密钥  1.0.5版本以后如果用到V2的接口时必填，单纯V3不需要
        app-secret: felordcn
        # api v3 密钥 必填
        app-v3-secret: 0e4efac*************5303ec
        # 微信支付商户号 必填
        mch-id: 1123****9
        # 商户服务器域名 用于回调  回调路径为 domain + notifyUrl  需要放开回调接口的安全策略 必填
        domain: https://felord.cn
        # 商户 api 证书路径 必填  填写classpath路径 位于 maven项目的resources文件下
        cert-path: wechat/apiclient_cert.p12