server:
  port: 8086
  servlet:
    context-path: /lottery

#########数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxxxxx:3306/lottery?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: xxxxxxx
    password: xxxxxxxx
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true
    profiles:
      active: wechat
#  profiles:
#    active: pro



#######mybatis-plus配置
mybatis-plus:
  mapper-locations: 'classpath*:mappers/**/*.xml'
  mapper-scan: 'com.cj.lottery'
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

########log4j日志配置
logging:
  config: classpath:logback-spring.xml
#  file:
#    path:

#######微信公众号配置信息
app:
  weixin:
    gzh:
      appid: wx4f43a6c5c3b7fe13
      secret: cb5d31f7c17c06e99b28bd39b5b289c1
    pay:
      appid: '22'
      mchid: '11'
      notifyUrl: ''
    refund:
      notifyUrl: '/lottery/api/pay/callbacks/refund'
  domain:
    url: https://bbox.92pr.cn/lottery

###### 阿里云短信
msg:
  account: xxxx
  password: xxxx
  sendMsgUrl: http://211.149.255.237:81/smsJson.aspx
#  templateCode: ''
#  paramName: ''


  ### 微信支付
wechat:
  pay:
    v3:
      # 租户id
      lottery:
        # 应用appId 必填
        app-id: xxxxxxxxxx
        # v2 api 密钥  1.0.5版本以后如果用到V2的接口时必填，单纯V3不需要
        app-secret: felordcn
        # api v3 密钥 必填
        app-v3-secret: xxxxxxxx
        # 微信支付商户号 必填
        mch-id: xxxxxxxx
        # 商户服务器域名 用于回调  回调路径为 domain + notifyUrl  需要放开回调接口的安全策略 必填
        domain: https://m.keyundz.cn
        # 商户 api 证书路径 必填  填写classpath路径 位于 maven项目的resources文件下
        cert-path: wechat/apiclient_cert.p12
#        notify-url: https://m.keyundz.cn/lottery/api/pay/callbacks/transaction

